services:
    novaway_feature_flag.collector.feature:
        class: Novaway\Bundle\FeatureFlagBundle\DataCollector\FeatureCollector
        public: false
        arguments:
            - "@novaway_feature_flag.manager.feature"
        tags:
            - { name: data_collector, template: "@NovawayFeatureFlag/data_collector/template.html.twig", id: "novaway_feature_flag.feature_collector" }
